name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Make mvnw executable
        run: chmod +x ./mvnw
        working-directory: Backend

      - name: Build JAR
        run: ./mvnw package -DskipTests
        working-directory: Backend

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: Clinicore
          environment_name: Clinicore-env-1
          region: us-east-2
          version_label: ${{ github.sha }}
          deployment_package: Backend/target/clinicore-0.0.1-SNAPSHOT.jar
          wait_for_environment_recovery: 120
          use_existing_version_if_available: true